//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfiniteDBEntities1 : DbContext
    {
        public InfiniteDBEntities1()
            : base("name=InfiniteDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<cityData> cityDatas { get; set; }
        public virtual DbSet<empdata> empdatas { get; set; }
        public virtual DbSet<ExcpetionLogDb> ExcpetionLogDbs { get; set; }
        public virtual DbSet<Stable1> Stable1 { get; set; }
        public virtual DbSet<Stable2> Stable2 { get; set; }
    }
}
