//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Client.TrialServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrialServiceReference.TrialWebServicesSoap")]
    public interface TrialWebServicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Web_Client.TrialServiceReference.HelloWorldResponse HelloWorld(Web_Client.TrialServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Client.TrialServiceReference.HelloWorldResponse> HelloWorldAsync(Web_Client.TrialServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name uname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        Web_Client.TrialServiceReference.SayHelloResponse SayHello(Web_Client.TrialServiceReference.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Client.TrialServiceReference.SayHelloResponse> SayHelloAsync(Web_Client.TrialServiceReference.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquareRoot", ReplyAction="*")]
        float SquareRoot(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquareRoot", ReplyAction="*")]
        System.Threading.Tasks.Task<float> SquareRootAsync(float f);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.TrialServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Web_Client.TrialServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.TrialServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Web_Client.TrialServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHello", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.TrialServiceReference.SayHelloRequestBody Body;
        
        public SayHelloRequest() {
        }
        
        public SayHelloRequest(Web_Client.TrialServiceReference.SayHelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uname;
        
        public SayHelloRequestBody() {
        }
        
        public SayHelloRequestBody(string uname) {
            this.uname = uname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.TrialServiceReference.SayHelloResponseBody Body;
        
        public SayHelloResponse() {
        }
        
        public SayHelloResponse(Web_Client.TrialServiceReference.SayHelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayHelloResult;
        
        public SayHelloResponseBody() {
        }
        
        public SayHelloResponseBody(string SayHelloResult) {
            this.SayHelloResult = SayHelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrialWebServicesSoapChannel : Web_Client.TrialServiceReference.TrialWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrialWebServicesSoapClient : System.ServiceModel.ClientBase<Web_Client.TrialServiceReference.TrialWebServicesSoap>, Web_Client.TrialServiceReference.TrialWebServicesSoap {
        
        public TrialWebServicesSoapClient() {
        }
        
        public TrialWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrialWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrialWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrialWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Client.TrialServiceReference.HelloWorldResponse Web_Client.TrialServiceReference.TrialWebServicesSoap.HelloWorld(Web_Client.TrialServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Web_Client.TrialServiceReference.HelloWorldRequest inValue = new Web_Client.TrialServiceReference.HelloWorldRequest();
            inValue.Body = new Web_Client.TrialServiceReference.HelloWorldRequestBody();
            Web_Client.TrialServiceReference.HelloWorldResponse retVal = ((Web_Client.TrialServiceReference.TrialWebServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Client.TrialServiceReference.HelloWorldResponse> Web_Client.TrialServiceReference.TrialWebServicesSoap.HelloWorldAsync(Web_Client.TrialServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Client.TrialServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Web_Client.TrialServiceReference.HelloWorldRequest inValue = new Web_Client.TrialServiceReference.HelloWorldRequest();
            inValue.Body = new Web_Client.TrialServiceReference.HelloWorldRequestBody();
            return ((Web_Client.TrialServiceReference.TrialWebServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Client.TrialServiceReference.SayHelloResponse Web_Client.TrialServiceReference.TrialWebServicesSoap.SayHello(Web_Client.TrialServiceReference.SayHelloRequest request) {
            return base.Channel.SayHello(request);
        }
        
        public string SayHello(string uname) {
            Web_Client.TrialServiceReference.SayHelloRequest inValue = new Web_Client.TrialServiceReference.SayHelloRequest();
            inValue.Body = new Web_Client.TrialServiceReference.SayHelloRequestBody();
            inValue.Body.uname = uname;
            Web_Client.TrialServiceReference.SayHelloResponse retVal = ((Web_Client.TrialServiceReference.TrialWebServicesSoap)(this)).SayHello(inValue);
            return retVal.Body.SayHelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Client.TrialServiceReference.SayHelloResponse> Web_Client.TrialServiceReference.TrialWebServicesSoap.SayHelloAsync(Web_Client.TrialServiceReference.SayHelloRequest request) {
            return base.Channel.SayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Client.TrialServiceReference.SayHelloResponse> SayHelloAsync(string uname) {
            Web_Client.TrialServiceReference.SayHelloRequest inValue = new Web_Client.TrialServiceReference.SayHelloRequest();
            inValue.Body = new Web_Client.TrialServiceReference.SayHelloRequestBody();
            inValue.Body.uname = uname;
            return ((Web_Client.TrialServiceReference.TrialWebServicesSoap)(this)).SayHelloAsync(inValue);
        }
        
        public float SquareRoot(float f) {
            return base.Channel.SquareRoot(f);
        }
        
        public System.Threading.Tasks.Task<float> SquareRootAsync(float f) {
            return base.Channel.SquareRootAsync(f);
        }
    }
}
