// <auto-generated />
namespace FluentAPI_Prj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class FluentAPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluentAPI));
        
        string IMigrationMetadata.Id
        {
            get { return "202606010724376_FluentAPI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
